### ISSUE TITLE
ss-libev 2.6.0 support obfs, but docker failed to start

### ISSUE THREAD

**Issue by j4Uq** [TommyLau/docker-shadowsocks#1]
https://github.com/shadowsocks/shadowsocks-libev/releases
https://github.com/shadowsocks/shadowsocks-org/issues/26
servcer cmd: 
ss-server -s 0.0.0.0 -p 233 -k ******** -m chacha20 --obfs http --fast-open
but docker failed to start, please update for this

**Comment by TommyLau** [comment]
I will have a look into this, thanks for your feedback.

**Comment by TommyLau** [comment]
After checking the official release page at: https://github.com/shadowsocks/shadowsocks-libev/releases

Currently 2.6.0 is still in `Pre-release` stage, for most of the users, stable is the first priority, so I'll check later to support 2.6.0+ when it is official in `Release` stage.

The latest version you can get from this Docker image is 2.5.6 now. Thanks.
